/**
 * Defines types of weapons.
 *
 * DO NOT EDIT THIS FILE
 * 
 * Don't be scared because this is an enum and not a class. Enums are just ways
 * of defining new data types much like we did in OCaml. The OCaml version of
 * this type would be:
 * 
 * type weapon =
 *   | AXE
 *   | MACE
 *   | SWORD
 *
 * As you can see, an enum is just a simple way of enumerating values of a
 * certain type.
 *
 * You can refer to the values of an enum like you would a static member of a
 * class, by naming the class followed by a dot followed by the value. For
 * example, there are three values of type Weapon, and they are written:
 *
 * Weapon.AXE
 * Weapon.MACE
 * Weapon.SWORD
 *
 * Values of an enum evaluate like primitives, so both of the following are
 * true:
 *
 * Weapon.AXE == Weapon.AXE
 * Weapon.AXE.equals(Weapon.AXE)
 */
public enum Sprite {
	LEFT,
	RIGHT,
	UP,
	DOWN
}
